import type { NextApiRequest } from 'next';

// The single source of truth for which routes the API key is allowed to call. Cookie/UI sessions
// are NOT restricted by this list.
//
// This lives in its own dependency-free module on purpose: verifyUser imports it, and
// verifyUser must stay lightweight (no transitive database-model imports), otherwise any
// test or code path that loads a route using verifyUser would pull sequelize into scope.
export const allowedApiRoutes = [
   'GET:/api/keyword',
   'GET:/api/keywords',
   'PUT:/api/keywords',
   'DELETE:/api/keywords',
   'GET:/api/domains',
   'POST:/api/keywords',
   'POST:/api/domains',
   'DELETE:/api/domains',
   'POST:/api/refresh',
   'POST:/api/cron',
   'POST:/api/notify',
   'POST:/api/searchconsole',
   'GET:/api/searchconsole',
   'DELETE:/api/searchconsole',
   'GET:/api/searchconsole/connect',
   'GET:/api/insight',
   'GET:/api/insights',
   'GET:/api/scoreboard',
   'GET:/api/entry-pages',
   'GET:/api/ai-referrals',
   'GET:/api/summary',
   'GET:/api/human-traffic',
   'GET:/api/human-analytics',
   'GET:/api/goals',
   'POST:/api/goals',
   'PUT:/api/goals',
   'DELETE:/api/goals',
   'GET:/api/goal-analytics',
   'GET:/api/conversion-attribution',
   'GET:/api/causal-links',
   'GET:/api/suggest-goals',
   'GET:/api/onboarding-status',
   'POST:/api/key-drop',
   'GET:/api/start-here',
   'GET:/api/striking-distance',
   'GET:/api/channel-report',
   'GET:/api/live-view',
   'GET:/api/funnel',
   'GET:/api/entry-page-report',
   'GET:/api/period-compare',
   'GET:/api/site-audit',
   'GET:/api/cannibalization',
   'GET:/api/content-gap',
   'GET:/api/content-performance',
   'GET:/api/weekly-digest',
   'GET:/api/executive-summary',
   'GET:/api/seo-report',
   'GET:/api/aeo-report',
   'GET:/api/aeo-roi',
   'GET:/api/campaign-report',
   'GET:/api/dashboard',
   'GET:/api/portfolio',
   'GET:/api/competitor-visibility',
   'GET:/api/segments',
   'POST:/api/segments',
   'DELETE:/api/segments',
   'GET:/api/segment-analytics',
   'GET:/api/breakdown',
   'GET:/api/timeseries',
   'GET:/api/events',
   'GET:/api/engagement',
   'GET:/api/ai-visibility',
   'GET:/api/top-clicks',
   'GET:/api/form-submissions',
   'GET:/api/scroll-depth',
   'GET:/api/page-engagement',
   'GET:/api/web-vitals',
   'GET:/api/conversions',
   'GET:/api/prompt-checks',
   'POST:/api/prompt-checks',
   'DELETE:/api/prompt-checks',
   'POST:/api/prompt-record',
   'GET:/api/prompt-radar',
   'GET:/api/discover',
   'POST:/api/onboard',
   'GET:/api/install-instructions',
   'GET:/api/briefing',
   'GET:/api/alerts',
   'GET:/api/daily-brief',
   'GET:/api/me',
   'GET:/api/export',
   'GET:/api/security',
   'GET:/api/help',
];

export const isAllowedApiRoute = (req: NextApiRequest): boolean => Boolean(
   req.url && req.method
   && allowedApiRoutes.includes(`${req.method}:${req.url.replace(/\?(.*)/, '')}`),
);
