#!/bin/sh
# Generate a .env for s33k with strong, random secrets so `docker compose up` just works.
#
# Safe to re-run: it will NOT overwrite an existing .env (delete .env first if you want
# fresh secrets). Requires `openssl`, which ships on macOS and virtually every Linux.

set -e
cd "$(dirname "$0")/.."

if [ -f .env ]; then
  echo ".env already exists. Not overwriting. Delete it first if you want fresh secrets."
  exit 0
fi

SECRET=$(openssl rand -hex 34)
APIKEY=$(openssl rand -hex 24)
PASSWORD=$(openssl rand -base64 18 | tr -dc 'A-Za-z0-9' | cut -c1-20)
PGPASS=$(openssl rand -hex 16)

cat > .env <<EOF
# Generated by scripts/setup-env.sh. Keep this file secret. It is gitignored.

# The single admin login for the web UI.
USER_NAME=admin
PASSWORD=$PASSWORD

# SECRET encrypts stored credentials and signs your login session.
SECRET=$SECRET

# APIKEY is the single Bearer token for the REST API and the MCP server.
APIKEY=$APIKEY

# Where the app is reachable. Change if you host it somewhere else.
NEXT_PUBLIC_APP_URL=http://localhost:3000
PORT=3000

# Postgres for the docker compose stack (internal network only, not exposed to your host).
POSTGRES_USER=s33k
POSTGRES_PASSWORD=$PGPASS
POSTGRES_DB=s33k

# Optional: your own Serper key for SEO rank tracking. You can also paste it in
# Settings after you log in. Get one free at https://serper.dev
SERPER_API_KEY=
EOF

echo "Wrote .env with fresh secrets."
echo
echo "  Admin login:      admin / $PASSWORD"
echo "  MCP / API key:    $APIKEY"
echo
echo "Save those. Next:"
echo "  docker compose up -d --build"
echo "then open http://localhost:3000"
