#!/bin/sh
# Generate a .env for s33k with strong, random secrets so `docker compose up` just works.
#
# Safe to re-run: it will NOT overwrite an existing .env (delete .env first if you want
# fresh secrets). Requires `openssl`, which ships on macOS and virtually every Linux.

set -e
cd "$(dirname "$0")/.."

if [ -f .env ]; then
  echo ".env already exists. Not overwriting. Delete it first if you want fresh secrets."
  exit 0
fi

SECRET=$(openssl rand -hex 34)
APIKEY=$(openssl rand -hex 24)
PGPASS=$(openssl rand -hex 16)

cat > .env <<EOF
# Generated by scripts/setup-env.sh. Keep this file secret. It is gitignored.

# SECRET encrypts stored credentials and signs the one-time setup and key-drop tokens.
SECRET=$SECRET

# APIKEY is the single credential: the Bearer token for the REST API and the MCP server.
APIKEY=$APIKEY

# Where the app is reachable. Change if you host it somewhere else.
NEXT_PUBLIC_APP_URL=http://localhost:3000
PORT=3000

# Postgres for the docker compose stack (internal network only, not exposed to your host).
POSTGRES_USER=s33k
POSTGRES_PASSWORD=$PGPASS
POSTGRES_DB=s33k

# Optional: your own Serper key for SEO rank tracking. You can also paste it on the
# one-time setup page (see the [SETUP] log line). Get one free at https://serper.dev
SERPER_API_KEY=

# Which SERP source scrapes rankings. "serper" pairs with SERPER_API_KEY above.
# Without this the scraper stays off and keywords never get a rank.
SCRAPER_TYPE=serper
EOF

echo "Wrote .env with fresh secrets."
echo
echo "  MCP / API key:    $APIKEY"
echo
echo "Save that key: it is the one credential your LLM connects with. Next:"
echo "  docker compose up -d --build"
echo "then read the one-time setup link from the logs:"
echo "  docker compose logs s33k | grep SETUP"
